-- Base de datos para ESX Advanced Weapons System

CREATE TABLE IF NOT EXISTS `weapon_licenses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner` varchar(60) NOT NULL,
  `license_type` varchar(50) NOT NULL,
  `expiry_date` datetime NOT NULL,
  `status` varchar(20) DEFAULT 'active',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `owner` (`owner`),
  KEY `license_type` (`license_type`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `custom_weapons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner` varchar(60) NOT NULL,
  `serial_number` varchar(100) NOT NULL UNIQUE,
  `weapon_model` varchar(100) NOT NULL,
  `weapon_type` varchar(20) NOT NULL,
  `components` longtext NOT NULL,
  `attachments` longtext NOT NULL,
  `stats` longtext,
  `durability` int(11) DEFAULT 100,
  `registered` tinyint(1) DEFAULT 0,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `owner` (`owner`),
  KEY `weapon_type` (`weapon_type`),
  KEY `serial_number` (`serial_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('weapon_frame', 'Armazón de Arma', 1.0, 0, 1),
('pistol_barrel', 'Cañón de Pistola', 0.5, 0, 1),
('metal', 'Metal', 0.3, 0, 1),
('pistol_grip', 'Empuñadura de Pistola', 0.2, 0, 1),
('stolen_frame', 'Armazón Robado', 1.0, 1, 1),
('illegal_barrel', 'Cañón Ilegal', 0.5, 1, 1),
('silencer', 'Silenciador', 0.3, 1, 1),
('custom_pistol_9mm', 'Pistola 9mm Personalizada', 1.5, 0, 1),
('custom_pistol_silenced', 'Pistola Silenciada Personalizada', 1.5, 1, 1),
('energy_core', 'Núcleo de Energía', 1.5, 1, 1),
('laser_emitter', 'Emisor Láser', 0.5, 1, 1),
('power_cell', 'Celda de Potencia', 0.8, 0, 1),
('advanced_circuit', 'Circuito Avanzado', 0.3, 1, 1),
('micro_energy_core', 'Micro Núcleo de Energía', 1.0, 1, 1),
('grip_module', 'Módulo de Empuñadura', 0.4, 0, 1),
('display_interface', 'Interfaz de Pantalla', 0.6, 1, 1),
('energy_emitter', 'Emisor de Energía', 0.7, 1, 1),
('advanced_energy_core', 'Núcleo de Energía Avanzado', 2.0, 1, 1),
('hud_optic', 'Mira HUD', 0.9, 1, 1),
('suppressor_module', 'Módulo Supresor', 1.2, 1, 1),
('rail_interface', 'Interfaz de Riél', 0.5, 0, 1),
('forward_grip', 'Empuñadura Delantera', 0.6, 0, 1),
('energy_cell', 'Celda de Energía 8mm', 0.3, 0, 1),
('energy_rdo7_energy_sidearm', 'RDO7 Energy Sidearm', 2.0, 1, 1),
('energy_tx_p1_energy_pistol', 'TX-P1 Energy Pistol', 1.8, 1, 1),
('energy_xz_74_energy_rifle', 'XZ-74 Energy Rifle', 3.5, 1, 1),
('reinforced_housing', 'Housing Reforzado', 1.2, 0, 1),
('spring_mechanism', 'Mecanismo de Resorte', 0.4, 0, 1),
('quick_release_latch', 'Cierre de Liberación Rápida', 0.2, 0, 1),
('dual_housing', 'Housing Dual', 2.0, 1, 1),
('advanced_spring', 'Resorte Avanzado', 0.6, 1, 1),
('reinforced_tower', 'Torre Reforzada', 0.8, 1, 1),
('high_grade_metal', 'Metal de Alto Grado', 0.5, 0, 1),
('drum_mag_xt1', 'Cargador Tambor XT-1', 2.5, 0, 1),
('dual_drum_mag_dp01', 'Cargador Tambor Dual DP-01', 4.0, 1, 1);
